
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo



###
DELETE  http://localhost:8080/api/users

### register
POST http://localhost:8080/api/auth/register 
Content-Type: application/json

{
    "username": "bally",
    "email": "abc.xyvbz@gmail.com",
    "password": "696jfhdsjfhds9"
}


### log in
POST http://localhost:8080/api/auth/login 
Content-Type: application/json

{
    "username": "bally",
    "email": "abc.xyvbz@gmail.com",
    "password": "696jfhdsjfhds9"
}

###
GET http://localhost:8080/api/auth/52746c70-be03-4b3f-8cf3-bada363e5042
### 
POST http://localhost:8080/api/auth/resend_token
Content-Type: application/json

{
    "email": "abc.xyvbz@gmail.com"
}


############################## Group
### Create new Group
POST http://localhost:8080/api/group
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "name": "first Group",
    "description": "dfbadsjkhfdshklfdksf",
    "url": "sxsdadfdf"
}

### Get all group
GET http://localhost:8080/api/group
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo

### Get group by Id
GET http://localhost:8080/api/group/e1ba6f29-f209-42ba-8913-a4cce0258ce2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo

### Edit group
GET http://localhost:8080/api/group/e1ba6f29-f209-42ba-8913-a4cce0258ce2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "name": "first Group edit",
    "description": "dfbadsjkhfdshklfdksf",
    "url": "sxsdadfdf"
}

### Delete group
DELETE  http://localhost:8080/api/group/971ebcca-9587-45b7-a51a-a3407164bc76
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo

### Join group
GET http://localhost:8080/api/group/id/join
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo

### Leave group
GET http://localhost:8080/api/group/id/leave
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo

### Add Member
POST http://localhost:8080/api/group/id/members
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "username": "bally",
}

### View all Member
GET http://localhost:8080/api/group/id/members
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo

### Remove Member
DELETE http://localhost:8080/api/group/id/members
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "username": "bally",
}


### Add Moderaotor
POST http://localhost:8080/api/group/id/moderators
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "username": "bally",
}

### View all moderators
GET http://localhost:8080/api/group/id/moderators
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo

### Remove moderators
DELETE http://localhost:8080/api/group/id/moderators
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "username": "bally",
}



### POST
### Create new Post
POST http://localhost:8080/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "title": "last Post",
    "summary": "sdfjkasdfjdshlfhasd",
    "category": 1,
    "description": "dfbadsjkhfdshklfdksf",
    "url": "sxsdadfdf"
}

### Get all Post
GET http://localhost:8080/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo

### Get Post by Id
GET  http://localhost:8080/api/post/0b20351d-7a66-4103-9acd-b207b4552502
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo

### Edit Post
PATCH http://localhost:8080/api/post/0b20351d-7a66-4103-9acd-b207b4552502
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "title": "first post edit"
}

### Delete Post
DELETE  http://localhost:8080/api/group/971ebcca-9587-45b7-a51a-a3407164bc76
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo



### Get Comments
GET  http://localhost:8080/api/comment/post/0b20351d-7a66-4103-9acd-b207b4552502
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo


### Create Comment  
POST  http://localhost:8080/api/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "text" : "bal ly er coment",
    "postId" : "0b20351d-7a66-4103-9acd-b207b4552502"
}

### Create Comment  
PATCH http://localhost:8080/api/post/0b20351d-7a66-4103-9acd-b207b4552502/comment/ea754970-0e7e-4f00-bdee-5dc6c6e90953
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "text" : "bal ly 2 coment"
}


### VOTE
POST http://localhost:8080/api/vote
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiYWxseSIsImlhdCI6MTY4MDQ1NzE5OCwiZXhwIjoxNjg4MjMzMTk4fQ.kpjz8pUoMwrz5C5NZEEiUDuJzRRXDbtQVLssUSN3TOo
Content-Type: application/json

{
    "voteType": 1,
    "postId" : "543b6738-858d-4168-8e13-68fbc223313b"
}


### swagger
GET  http://localhost:8080/v3/api-docs
